---
# tasks file for sa-box-bootstrap-win

  - name: Bootstrap | Install win_dsc custom resources
    win_psmodule:
      name: "{{item}}"
      state: present
    with_items: "{{windsc_resources}}"

  - name: Bootstrap | set default timezone to {{timezone}}
    win_timezone:
      timezone: "{{timezone}}"
    when: timezone is defined

  - name: Bootstrap | Ensure NetFramework 3.5 installed
    win_dsc:
      resource_name: WindowsFeature
      name: NET-Framework-Core
      ensure: present

  - name: Bootstrap | Install choco
    win_dsc:
      resource_name: cChocoInstaller
      InstallDir: "{{choco_install_dir | default('c:\\choco')}}"
      DependsOn: "[WindowsFeature]NetFrameworkCore"
    when: option_install_choco

  - name: Bootstrap | Install core choco packages
    win_dsc:
      resource_name: cChocoPackageInstaller
      Name: "{{item}}"
      DependsOn: "[cChocoInstaller]installChoco"
    with_items: "{{choco_core_packages}}"
    when: option_install_choco

  - name: Bootstrap | Install custom choco packages
    win_dsc:
      resource_name: cChocoPackageInstaller
      Name: "{{item}}"
      DependsOn: "[cChocoInstaller]installChoco"
    with_items: "{{choco_custom_packages}}"
    when: option_install_choco

  - name: Bootstrap | Install windows features for IIS
    win_dsc:
      resource_name: WindowsOptionalFeature
      name: "{{item}}"
      ensure: Enable
    with_items: "{{windows_iis_features}}"
    when: option_install_iis_features

  - name: Bootstrap | Install windows features for ASP.NET
    win_dsc:
      resource_name: WindowsOptionalFeature
      name: "{{item}}"
      ensure: Enable
    with_items: "{{windows_aspnet_features}}"
    when: option_install_aspnet_features


  - include_tasks: tasks_install_roaming_profile.yml
    when: option_install_roaming_profile
