---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..
    - ansible_connection: winrm
    - ansible_ssh_port: 5986
    - ansible_winrm_server_cert_validation: ignore
    - ansible_winrm_transport: ssl

  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: gather facts
      setup:

  roles:
     - {
         role: "sa-box-bootstrap-win",
         timezone: "Central European Standard Time",
         option_install_roaming_profile: true,
         powershell_roaming_profile: "https://github.com/Voronenko/winfiles.git"
       }


  tasks:

    - debug: msg="Tasks section"
